### ISSUE TITLE
This package is not up to date with upstream.

### ISSUE THREAD

**Issue by marcinant** [components/webfontloader#1]
This component version is 1.5.2 while upstream is 1.6.3. Is there any chance to upgrade?

**Comment by RobLoach** [comment]
@marcinant If you send up a pull request, one of the many maintainers would be glad to merge and tag :+1: .

**Comment by marcinant** [comment]
Sure. However can I change name of main script to `webfontloader.js` just like an original one?

**Comment by RobLoach** [comment]
> can I change name of main script to webfontloader.js just like an original one?

Of course! As long as references are updated.

**Comment by marcinant** [comment]
PR sent.

**Comment by RobLoach** [comment]
Tagged! Thanks a lot, @marcinant :+1:
